### ISSUE TITLE
overloading assignment operator to work with cv::Mat

### ISSUE THREAD

**Issue by ayikahmet** [ConstantRobotics-Ltd/Frame#6]
In many applications where we use opencv, we generally transfer data between Frame class and cv::Mat. To make that easier "=" operator may be used, for example

Frame = cv::Mat;
or
cv::Mat = Frame;

In order to not make Frame library directly depend on opencv, we can check if system has opencv (inside Cmake) then use preproccessor (#ifdef) to compile with this feauture, if system doesnt have opencv it wont affect usual working of Frame class.

**Comment by ConstantRobotics** [comment]
Frame should not have dependencies from OpenCv
